#ifndef MINIGIT_H
#define MINIGIT_H

#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

#define MINIGIT_INIT_DIR ".minigit"
#define MINIGIT_HOOKS_DIR "hooks"
#define MINIGIT_INFO_DIR "info"
#define MINIGIT_OBJECTS_DIR "objects"
#define MINIGIT_OBJECTS_INFO_DIR "objects/info"
#define MINIGIT_OBJECTS_PACK_DIR "objects/pack"
#define MINIGIT_REFS_DIR "refs"
#define MINIGIT_REFS_HEADS_DIR "refs/heads"
#define MINIGIT_REFS_TAGS_DIR "refs/tags"
#define MINIGIT_OBJECTS_PATH MINIGIT_INIT_DIR "/" MINIGIT_OBJECTS_DIR

#define MINIGIT_CONFIG_FILE "config"
#define MINIGIT_DESCRIPTION_FILE "description"
#define MINIGIT_HEAD_FILE "HEAD"
#define MINIGIT_INFO_EXCLUDE_FILE "info/exclude"

#define MINIGIT_INIT_DIRS_COUNT 8
#define MINIGIT_INIT_DIRS \
    MINIGIT_HOOKS_DIR, MINIGIT_INFO_DIR, MINIGIT_OBJECTS_DIR, MINIGIT_REFS_DIR, \
    MINIGIT_OBJECTS_INFO_DIR, MINIGIT_OBJECTS_PACK_DIR, \
    MINIGIT_REFS_HEADS_DIR, MINIGIT_REFS_TAGS_DIR

#define MINIGIT_INIT_FILES_COUNT 4
#define MINIGIT_INIT_FILES MINIGIT_CONFIG_FILE, MINIGIT_DESCRIPTION_FILE, MINIGIT_HEAD_FILE, MINIGIT_INFO_EXCLUDE_FILE

#define MINIGIT_HEAD_INITIAL_CONTENT "ref: refs/heads/main\n"

#endif
